# Project: MazeLock
# Makefile created by Dev-C++ 5.6.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.o ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.o
LINKOBJ  = ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.o ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -lgraphics -lgdi32 -limm32 -lmsimg32 -lole32 -loleaut32 -lwinmm -luuid  -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = ChainingDemo.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.o: ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.cpp
	$(CPP) -c ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.cpp -o ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/MazeLock.o $(CXXFLAGS)

../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.o: ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.cpp
	$(CPP) -c ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.cpp -o ../../ege-13.04.02-full/man/netfriendsdemo/MazeLock/wysaid.o $(CXXFLAGS)
